[tool.ruff]
# Enable rules
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
]

# Ignore specific rules
ignore = []

# Allow fixes for all enabled rules
fix = true

# Exclude files
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "build",
    "dist",
]

# Line length
line-length = 120

[tool.ruff.lint.isort]
known-first-party = ["callbacks", "models", "data", "validation", "train", "utils"]
