wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719119528
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 7
      - 23
      - 66
      4: 3.10.14
      5: 0.17.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
token_dim:
  desc: null
  value: 5120
d_model:
  desc: null
  value: 256
nhead:
  desc: null
  value: 8
d_hid:
  desc: null
  value: 1024
nlayers:
  desc: null
  value: 4
output_dim:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 141552
gradient_accumulation_steps:
  desc: null
  value: 1
compiled:
  desc: null
  value: false
num_datasets:
  desc: null
  value: 2
dataset_embedding_dim:
  desc: null
  value: 16
max_lr:
  desc: null
  value: 0.0004
