name: PertSets
checkpoint: null
device: cuda

kwargs:
  cell_set_len: 512
  blur: 0.05
  hidden_dim: 328
  loss: energy
  confidence_head: False
  n_encoder_layers: 4
  n_decoder_layers: 4
  predict_residual: True
  softplus: True
  freeze_pert: False
  transformer_decoder: False
  finetune_vci_decoder: False
  residual_decoder: False
  batch_encoder: False
  nb_decoder: False
  mask_attn: False
  distributional_loss: energy
  init_from: null
  transformer_backbone_key: qwen3
  transformer_backbone_kwargs:
      max_position_embeddings: ${model.kwargs.cell_set_len}
      hidden_size: ${model.kwargs.hidden_dim}
      intermediate_size: 1312
      num_hidden_layers: 8
      num_attention_heads: 8
      use_cache: false
